#!/bin/bash
sudo docker run -d -p 8080:8080 --name jenkins --hostname msrit docker_jenkins
#sudo docker exec -it jenkins cat /var/lib/jenkins/secrets/initialAdminPassword

sudo docker-compose up -d mongodb app

sudo docker network connect --ip 9.9.2.1 docker_connexion-vpc jenkins
